<?php
class Guerrier extends Personnage{
    public function  recevoirDegats(){
        /*return parent::recevoirDegats();*/ // TODO: Change the autogenerated stub
        if ($this->degats >= 0 && $this->degats <= 100){
            $this->degats += $this->degats * 4;
        }else{
            echo 'PPL2';
        }

        if ($this->degats >= 100){
            return self::PERSONNAGE_TUE;
        }
        return self::PERSONNAGE_FRAPPE;
    }
}